#+setupfile: ~/COMM/public_html/org-html-theme/index-bigblow-header.setup
#+include: ~/COMM/Lects/site/info/common-header.org
#+title: 抽象化のための手続き

  origin: [[https://mitpress.mit.edu/sicp/full-text/sicp/book/node4.html][SICP]]

* 抽象化のための手続き
  
  簡単な思い付きを越えて，その力を発揮する，心の働きは，次の三つのこと
  からなる:

1. いくつかの簡単なアイディアを一つにまとめること。

   複合的なアイディアが生まれる。

2. ふたつのアイディアをつなげ，一つにまとめることなしに二つのアイディ
   アを一緒に見る。

   *関係*というアイディアが生まれる。

3. それを，実在に伴なうすべての他のアイディアから切り離す。

   これは*抽象*と呼ばれ，すべてのアイディアはこのように生まれる。

* Building Abstractions with Procedures
  


The acts of the mind, wherein it exerts its power over simple ideas,
are chiefly these three:

1. Combining several simple ideas into one compound one, and thus all
   complex ideas are made.

2. The second is bringing two ideas, whether simple or complex,
   together, and setting them by one another so as to take a view of
   them at once, without uniting them into one, by which it gets all
   its ideas of relations.

3. The third is separating them from all other ideas that accompany
   them in their real existence: this is called abstraction, and thus
   all its general ideas are made.

    John Locke, An Essay Concerning Human Understanding (1690)


