* [[https://www.lifehacker.jp/2014/06/140601eisenhower.html][アイゼンハワー元大統領から学ぶ、時間・感情・仕事の管理術]]

*** 時間管理のための｢アイゼンハワー意思決定マトリクス｣

#+BEGIN_QUOTE

  大事なことは緊急であることはほとんどなく、緊急なことが大事であること
  もほとんどない。

#+END_QUOTE

1. 重要＋緊急：すぐにやる個人的なこと
2. 重要＋緊急でない：一日の終わりにやる個人的なこと
3. 重要でない＋緊急：人に任せること
4. 重要でない＋緊急でない：どうでもいいこと

本当に重要なのは、緊急と重要の違いを明確にするところです。

#+BEGIN_QUOTE

  緊急なことというのは、すぐに対応しなければならないことです。ToDoリス
  トで｢至急！｣と書いてある仕事では、自己防衛的、ネガティブ、慌ただしい、
  視野が狭くなっている、すぐに反応するモードです。

  重要なことというのは、長期的な目標や使命、価値、目的を達成するための
  ものです。重要なことが緊急であることもありますが、大体はそうではあり
  ません。重要なことに集中する時は、落ち着いていて、合理的で、新しい機
  会に対してもオープンに対応するモードです。

#+END_QUOTE

*** ネガティブな感情を忘れるために使う｢怒りの引き出し｣

怒りというのは驚くほど苛立たしい感情です。
この問題に対処するために｢怒りの引き出
し｣と呼ぶ方法を使っていました。

#+BEGIN_QUOTE

  私は、できるだけ嫌いな人を作らないように心がけていました。誰かが、自
  分に対して見下したような態度をとったことに後ろめたい気持ちを持ってい
  るとしたら、私はその人のことを忘れるようにします。

  少しわざとらしいとはわかっていますが、次のようなことをよくやっていま
  した。その人の名前を紙に書いて、机の一番下の引き出しに入れます。そし
  て自分にこう言うのです。｢仲間だと思うなら、これは終わったことだ｣。長
  い間をかけてこの引き出しは、誰かに対する恨みを粉々にして捨てる、個人
  的なゴミ箱のようなものになっていきました。

#+END_QUOTE

*** 賢い人を近くに置き、任せることを学ぶ

アイゼンハワーは、自分が一番かしこい人間ではないという事実を、かたくな
に信じている人でした。

#+BEGIN_QUOTE

  常日頃から、自分よりも多くのことを知っている人、自分よりもうまくでき
  る人、自分よりも明晰な人と仲良くし、その人たちからできる限り学びなさ
  い。

#+END_QUOTE

同じように、アイゼンハワーは権限委譲の支持者でもありました。

#+BEGIN_QUOTE

  スタッフでも内閣でも議会でも、周りの人間は常に期待をしているが、私が
  決断をしなければならないものというものは無い。委譲された権限の範囲で、
  制定されている政策の中で、自分なりに問題を解決してほしい。私がこのよ
  うな主張をするのは、任命した人に一度でも訓告を与えたなら、次にその人
  が失敗した時は代わりの人を探すからだ。

#+END_QUOTE
