* 人に教えるときに気をつけている10のこと

   http://topisyu.hatenablog.com/entry/teaching

** 相手が話を聞くタイミングかを確認する

   相手が聞くタイミングでないときに話しても効果が薄いです。相手が精神的
   に、肉体的に話を聞ける状態でない時はぐっと我慢します。また、その人が
   失敗してからすぐならまだしも、あまり期間を空けすぎると「なぜそんな昔
   の話を」と思われるので、鉄は熱いうちに打つようにしたいですね。

** 自分が伝えたいことか、本人が聞きたいことかを考える

   教えようとする前に、今自分が教えたいことは本人のニーズがあるものかを
   考えます。本人のニーズはないけれど、自分がどうしても伝えたいことを教
   えるのは、自分のエゴなので、「これはどうしても聞いて欲しいのだけれど」
   と枕をつけます。教える方が偉いわけではないですから。

** 本人の立ち位置を確認する

   この話を聞くのは初めてか、日本人か外国人か、高等教育を受けているか、
   特定の主義・信仰があるかなど、どこから話をスタートするかを検討するた
   めに必要であれば確認します。ある程度関係性があるならまだしも、不特定
   多数への講演を依頼された時には、「○○という言葉はご存知ですか？」とい
   うようにキーワードについて知っているか知らないかを何回か質問してみて、
   聞き手の水準を把握します。
 
   ここまではどちらかというと教える前の準備段階のようなものでしょうか。
   ここからが、教える段になってからの話。

** これを学ぶと良いメリットを伝える

   その人が実現したいことにこの学びがどう繋がるかをできるのであれば説明
   する。実利があれば意欲が湧きやすいですし、教えている方も軸がぶれませ
   ん。

** まず全体像を説明する

   各論から入ってしまうと、聞き手の頭の中に地図ができず、断片的な知識を
   植え付けることになってしまいがちです。（そういう知識は忘れやすい。）
   可能であれば、全体像からブレークダウンして各論に入るような流れにした
   いですよね。

** 適度に抽象化、具体化する（例示する）

   理論を説明してすぐに理解できる人もいれば、事例を繰り返し聞いて腹落ち
   する人もいます。相手の能力に合わせて、例示の分量を加減します。
 
   本筋は上のようなもので、後は以下のようなことも気を付けます。

** 口で説明するだけではなく図解を厭わない

   口で話すのが一番楽ですが、相手の理解度を高めるためには、紙に書いた
   り、図にすることを面倒くさがらないようにします。口で言って理解しな
   ければ結局時間の無駄ですから、相手が理解できるための方法は何でも検
   討します。

** 分かってないことを定期的に確認

   聞き手が分かっていないのに、次々と話を進めるのはお互いにとって時間の
   無駄であり、大変不幸なことなので、細かなタイミングで習熟状況を確認し
   ます。

   「分かっていますか？」という質問は分かっていないことを確認する
   方法としては不適切なので（相手が誤解して理解しているかもしれませんし、
   相手が分かっていないことを恥として「分かっている」と言ってしまうこと
   がある）

   「では、ここまでの知識を使うと、このケースはどのように考え
   られますか？」というように、内容に関して理解しているかを質問します。

** 質問を誉め質問しやすい空気を作る

   質問しようと考えること、質問の回答を受け取ることで飛躍的に理解は進むの
   で、質問しやすい空気を作ることは大切です。

   質問をしてもらえることで、8をわざわざすることもないですし。ですので、
   質問してきたら、「それ、いいポイントですね」などと一言誉めてから回答
   をするようにします。質問することの喜びを感じてもらうようにします。

** 繰り返しを面倒くさがらない
