* org-Docs
** 人に教える"勉強法   [[:https://www.nhk.or.jp/hanamichi/p2013/130520.html][NHK テストの花道 - 過去の放送 -「"人に教える"勉強法」]] 
  [2017-11-03 金]

単純な用語や年号は覚えられるのに、その内容を踏み込んで聞かれると答えら
れない。そんなキミにオススメするのが、"人に教える"勉強法。知識を受身で
頭にインプットするのではなく、人に教えることを意識しながら学ぶと、より
深く理解でき、頭にもしっかり定着するぞ。

*** 概要

    記述問題が解けない！

    - 事件の背景や原因について文章で説明する記述問題となるとからっきしダ
      メ！という人がたくさんいる。

    - 「丸暗記」では解けないからだ。

    人に教えることを意識して勉強する

    - 本を読んだり、書き写したりするのに比べ
    - 知識の理解度や記憶の定着が大きく変わってくる

*** 人に教える勉強法1「リポーター法」

「人に教える勉強法」とは具体的にどうすればいいのか。
 - キーワードは、「勉強を取材だと思え！」だ。 
- つまり、教科書や授業に、取材するつもりで向き合いストーリーを作るようにしよう。

取材と言えばリポーター。リポーターが、事がらを説明する際次のような要素で構成していることに、気付いているかな？

- まずは「見出し」でテーマや問いを立て、
- 「内容」で何のことかを説明。
- 次に何故そうしたか「理由」を言って、
- どうなったかその「影響」を伝え、
- 最後に「結論」という流れだ。

覚え方は、
- 「み・な・り・せぇい・けつ（身なり清潔）」！ 影響の「えい」はちょっと無理があるけど是非覚えてくれ！

**** 実践リポート「関ヶ原の戦い」

凄腕リポーターに、歴史上の出来事をリポーター法で実況してもらったぞ。

- 見出し

  事件です！運命の決戦！徳川家康が関ヶ原の戦いで日本を統一しました。

- 内容

  ※関ヶ原の戦いとは何なのか？

  この事件は、1600年、徳川家康を中心に福島正則、黒田長政の東軍とそれに反対する石田三成、毛利輝元率いる西軍が　関ヶ原で戦った一大バトルの事ですね！　

- 理由

  ※なぜ関ヶ原の戦いが起きたのか？

  そもそも、信長の死後、秀吉に関東に移されていた家康は、「いつかトップ
  に立ってやろう！」と"鳴かぬなら鳴くまで待とうホトトギス"とばかりに我
  慢に我慢を重ね、天下を狙っていました。

- 影響

  ※関ヶ原の戦いによって何が起きたのか？

  天下分け目の戦いとなった関ヶ原の戦いを制した家康は、その後、征夷大将軍となり江戸幕府を開くこととなります。

- 結論

  ※その結果どうなったのか？

  敵対する豊臣派を一度にやっつけることが出来、家康は確固たる権力を手に入れることが出来たのです。

**** リポーター法活用ステップ

- ステップ1：教科書の中からリポーター法の要素に使えそうな部分をマーキング。

  ※アンダーラインを引いたり丸で囲んだり、自分なりのルールを決めてやってみよう。

  ※教科書だけでは足りないと感じたら資料集などから情報をゲットしよう。

- ステップ2：マーキングした中からリポータ―法で実際に使う部分を選び出す。

  これまでは教科書のどこが重要なのかわからなかったキミ。リポーター法を
  使うとポイントとなる部分がクッキリと浮かび上がってくるはずだ。

*** 人に教える勉強法2「人に教えるつもりでしゃべる」

書くだけではなく、話すことで五感を使うようになり、記憶率が高くなるとい
う。声に出して言うことで、説明したことが実体験として残る。つまり、記憶
として定着しやすいのだ。

**** しゃべって教えるコツ

- 問いをたてる

  「そもそもなになのか」「なぜ～なのか」という疑問から入ることによって、
  理由や根拠を考えていくことになる。そうすることで、相手も興味を掻き立
  てられやすいく、自分の頭も整理されて、記憶しやすくなる。

   ※相手の興味をかき立てるようにキミもリポーター法で考えた「見出し」をチェックしてみよう！

- 砕けた表現に言い換える

  誰にでもわかるよう簡単な表現に換えることで相手に伝わりやすくなるぞ。

- 分量を小分けにしてメモを見ずにしゃべる

  分量を小分けすることによって、ストーリーが確実に頭に入りやすく、自分
  でも理解できているかどうかをチェックしやすくなる。

  声に出してみて、つっかえた所が覚えていない所だ。声に出すことで自分が
  ちゃんとわかっていない部分を把握できるぞ。ちなみにボイスレコーダーを
  使って自分の説明を録音すれば、1人でそれを聞き返して、理解度をチェッ
  クできる。そして友だちと2人なら、楽しく教え合う事ができお互い、勉強
  の理解度アップにつながる！

