* 人を行動させる文章を書くための6つの型（PREP法、PASONAの法則など）

  これらは、読み手の行動を促すコピーライティングやセールスライティング
  に用いられる文章構成のひな形です。

  コピーライティングやセールスライティングに最適な6つの文章構成のひな形

INDEX

* PREP法（フレップ法）
* QUESTの法則（クエストの法則）
* AIDMAの法則（アイドマの法則）
* PASONAの法則（パソナの法則）
* CREMAの法則（クレマの法則）
* SDS法（エスディーエス法）

* コピーライティングの型は使い分ける！

** PREP法（フレップ法）

PREP法はコピーライティングに限らず、文章構成の雛型としてビジネス文書などでもよく用いられます。

結論(Point)、理由(Reason)、具体例(Example)、再結論(Point)の4つの単語の頭文字をとって名付けられ、PREP
法を用いることで簡潔で説得力のある文章の作成ができます。

1. 結論(Point)

   はじめに結論として文章内の趣旨をシンプルに伝えることで、読者にとって読みやすくなります。

2. 理由(Reason)

   続いて、結論に至った理由や背景、メリット、デメリットを伝えて、冒頭の結論を読者に納得してもらいます。

3. 具体例(Example)

   次に、具体例を述べることで結論が根拠付けられ、文章の内容を読者に信
   頼してもらいます。

4. 再結論(Point) 

   最後に再度結論に戻り、「だから〇〇」と伝えることで、読者は筆者の主
   張を納得・信頼・理解できます。

PREP法の型に沿った文章は、簡潔でありながら、しっかりと根拠付けされた説
得力のあるものになります。

通常、文章作成が不慣れな人が文章を書くと、要点が定まらず、読み手にとっ
て非常に読みにくい文章になることが多々あります。しかし、PREP法は初心者
でもスムーズに読みやすい文章を書けることが特徴です。

** QUESTの法則（クエストの法則）

QUESTの法則は、消費者心理の流れに沿った文章モデルで、セールスレターや
ランディングページによく用いられます。そのため、読者に何か商品を販売す
る目的を持った、消費行動を促す時に向いています。

QUESTの法則は、絞り込み(Quality)、共感(Understand)、啓発(Educate)、興
奮(Stimulate)、変化(Transition)の5つの単語の頭文字を取って名付けられて
います。

1. 絞り込み(Quality)

   まず読者を絞り込むことで、見込み客かそうでないかを選別します。絞り
   込みでは「自分のことだ」と読者に思わせることが大切で、はじめに「〜
   ではないですか？」と質問形式な文章が効果的です。

2. 共感(Understand)

   続いて、共感の部分で相手の悩みに対して理解し、同情してあげます。そ
   してその悩みをこのまま放置することの危険性を指摘して、読者に「どう
   すればいいの？教えて」と思われるようにします。

3. 啓発(Educate)

   啓発の部分では、商品のメリットを説明して、購入することの妥当性を示
   します。証拠となるデータを提示すると効果的です。

4. 興奮(Stimulate) 

   興奮の部分では、読者に商品購入後の未来を想像させます。それと同時に、
   商品を購入しなかった場合のマイナスなイメージも想像させることで、購
   買意欲の促進を狙います。

5. 変化(Transition)

   最後に、見込み客から顧客へ変化させるためにクロージングを行います。
   注文フォームを掲載して購入の後押しをすると効果的です。

このように、見込み客の読者に対して、悩みを深掘りした後に商品を紹介する
ことで、成約につなげやすくする構成となっています。QUESTの法則は、読者
の中でも、自分の悩みをある程度理解している人に対して、強い効果が期待で
きます。

** AIDMAの法則（アイドマの法則）

AIDMAの法則は、消費者が商品などのモノを認知して、そこから実際に購入に
つながるまでの消費活動プロセスのひとつで、マーケティング戦略を考えるモ
デルとして扱われています。ライティングにおいても、QUESTの法則と同様に
消費行動の促進につながる型で、セールスコピーなどに利用されます。

消費者が商品を購入するまでの過程となる「注意(Attention)、関心
(Interest)、欲求(Desire)、記憶(Memory)、行動(Action)」の5つの単語の頭
文字を取って名付けられています。

1. 注意(Attention)

   まずは、商品を紹介して知ってもらいます。ここで読者の好奇心を煽るこ
   とで、より注意を引きやすくなります。

2. 関心(Interest)

   続いて、消費者に商品への興味を持ってもらう段階です。どういう商品な
   のか、どんな悩みを解決できるのかを簡潔にわかりやすく伝えます。ここ
   で「自分のための商品だ」と思ってもらうのが理想です。

3. 欲求(Desire)

   次は商品を知った相手に「購入したい」と思ってもらう段階です。そのた
   め、商品購入後の未来や悩みが解決した後の状態を想像させられればベス
   トです。

4. 記憶(Memory)

   消費者の中にある「欲しい」という記憶を再度呼び起こす段階です。悩み
   の具体的な解決策を証明すると、「あ、やっぱり購入したい」と思っても
   らいやすくなります。

5. 行動(Action)

   この段階では、すでに消費者は既に商品購入の意思を強めています。最後
   の後押しとして、購入するためのフォームを設置するなど、消費者の消費
   行動を促します。

AIDMAの法則は、セールスコピーを書く上で基礎的な文章モデルですが、あく
までも商品購入までのプロセスを想定したものなので、コピーライティングの
効果はやや薄いと思われます。

ただし、AIDMAの法則は消費行動を体系化しており、消費者心理を理解するた
めには大切な手法です。

** PASONAの法則（パソナの法則）

PASONAの法則は、QUESTの法則、AIDMAの法則と同様に消費行動の促進が行えま
す。セールスレターやランディングページの他に、ブログ記事やメルマガ、プ
レゼンのトークスクリプトなど、多方面で用いられる手法です。

問題(Problem)、親近感(Affinity)、解決策(Solution)、提案(Offer)、絞り込
み(Narrowdown)、行動(Action)の6つの単語の頭文字を取って名付けられた法
則で、現在では新PASONAの法則とも呼ばれます。

1. 問題(Problem)

   まずは問題の段階で、読者の悩みを明確にします。ここで、読者自身も気
   づいていない潜在的な悩みを掘り下げると、相手をより惹きつけることが
   できます。

2. 親近感(Affinity)

   続いて相手に抵抗感をなくしてもらうために、自分もあなたの仲間だとい
   うことを認識してもらいます。読者の不安や悩みを共感してあげ、同じ目
   標を持っていることを証明します。

3. 解決策(Solution)

   共感した後はその悩みが解決できる方法を教えてあげます。写真やデータ
   など、目に見えてわかる証拠を提示できるとより効果的です。

4. 提案(Offer)

   悩み解決につながる商品の内容を示します。価格や効果を具体的に伝え、
   悩みが解決できる証明をすることで、商品の有用性を見せることが大切で
   す。

5. 絞り込み(Narrowdown)

   次に読者を見込み客に絞り込みます。特に「20名様限定」「あと3日まで」
   など、限定性を設けることで、これまで文章を読んでいただけの読者に、
   「商品を購入したい」という気持ちになってもらいます。

6. 行動(Action)

   商品購入までの最後の一押しです。「今回限り」など、今すぐ行動するべ
   き理由を明確にし、商品購入の妥当性を示します。

消費行動を促す文章の型はいくつかありますが、PASONAの法則は、中でも特に
消費行動を駆り立てやすい強いコピー文章の作成が可能です。

ただし、物事を掘り下げて書くことになるので、どうしても長文になりやすい
という欠点があります。

** CREMAの法則（クレマの法則）

CREMAの法則は、消費者の行動を促進する文章の型です。

PASONAの法則と同様に、セールスレターやランディンブページ、メルマガなど
さまざまな場面で用いられます。PASONAの法則よりも端的で短い文章で書ける
ので、どうしても最後まで読んで欲しいときに最適です。

結論(Conclusion)、理由(Reason)、証拠(Evidence)、手段(Method)、行動
(Action)の5つの単語の頭文字を取って名付けられたもので、文章構成はPREP
法によく似ています。

1. 結論(Conclusion)

   PREP法と同様、まずは結論から話すことで読者は文章の趣旨を理解し、読
   みやすくなります。

2. 理由(Reason)

   続いて結論に至った理由を説明し、読者の理解を深めます。ここでメリッ
   トとデメリットを伝えると、より主張の強い文章となります。

3. 証拠(Evidence)

   次に、その理由を根拠づけるために証拠を提示します。文章に信頼性が増
   し、読者に初めの結論に納得してもらいます。

4. 手段(Method)

   初めの結論で示した内容について、どうすれば達成できるのか、ここでは
   手段を明確にします。手段の具体的な方法は、読者が簡単に実践できるも
   のが次の行動の段階で有効的です。

5. 行動(Action)

   最後に、実際に行動することを促します。ただ促すだけでなく、「今すぐ
   に」という言葉を添えると、より読者を行動的にできます。

CREMAの法則は、消費行動を促す型の中でも、どちらかといえば相手に変化を
与えたいときに用いられます。例えば、メルマガに登録してもらいたいときや、
次の記事を続けて読んでもらいたいときなどに効果的な手法です。

** SDS法（エスディーエス法）

SDS法は、相手に素早く物事を伝えたいときに適しています。

短文のメルマガをはじめ、テレビのニュース番組や情報番組等でもよく利用さ
れている手法です。

概要(Summary)、詳細(Details reason)、まとめ(Summary)の3つの単語の頭文
字を取って名付けられたもので、同じような内容をあらゆる角度から3度伝え
る文章の型です。

1. 概要(Summary)

   はじめに記事の要約を伝えます。

2. 詳細(Details reason)

   概要の詳しい内容を理由や背景、メリット、デメリットを加えて具体的に
   説明します。詳細のパートは複数作成可能で、箇条書きにすると読者によ
   り伝わりやすくなります。

3. まとめ(Summary)

   文章の内容を改めて端的に述べます。事実や過去の事例から根拠づけると効果的です。

SDS法は、理解しやすく、記憶に残しやすいという特徴があります。相手に消
費行動を促すというよりも、最後まで文章を読んでもらいたいときにおすすめ
です。

** コピーライティングの型は使い分ける！

型の使い分けは以下がおすすめです。

   - QUESTの法則・AIDMAの法則・PASONAの法則：読者の消費行動を促したいとき

   - PREP法・SDS法：とにかく相手に物事を伝えたいとき

   - CREMAの法則：相手に単純行動を促したいとき
     それぞれの型を使い分けて、読者の行動を促すコピー文章を作成しましょう。

